### ISSUE TITLE
Running image from docker into lxc

### ISSUE THREAD

**Issue by awaisaz** [cryptofuture/lxd-image-xenial-light#1]
I want to do some comparison tests between docker and lxc. I have an image on Docker hun, which i want to import and run on lxc. For this reason I installed Skpeo, umoci, go-md2man and jq. when I try to run the command lxc-create c1 -t oci – --url docker://awaisaz/test:part2
it gives trust policy error. /etc/containers/policy.json not such file or directory.

Is there any other way to do it or a solution?

**Comment by cryptofuture** [comment]
Idk how its related to the image. But running process in the lxd container is just as running it on the host. There should be no any difference in performance unless you messed up lxd backend storage configuration. Its good idea to just use btrfs. lvm would be slightly slower than running on host fs with directory backend like extr4/xfs or btrfs.
